version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  go-api:
    build: ./go-api
    container_name: go-api
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/     # used later by adapter
    ports:
      - "8080:8080"

  python-consumer:
    build: ./python-consumer
    container_name: python-consumer
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
