
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  go-api:
    build: ./go-api
    container_name: go-api
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
      AMQP_QUEUE: southpark_messages
    ports:
      - "8080:8080"

  python-consumer:
    build: ./python-consumer
    container_name: python-consumer
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
      AMQP_QUEUE: southpark_messages
